version: '3'

services:
    node_app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"      
        volumes: 
            - .:/app
            
    node_tests:
        build:
            context: .
            dockerfile: Dockerfile.dev     
        volumes: 
            - .:/app
        command: ["npm", "run", "test"]